<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <AssemblyName>btrecv</AssemblyName>
    <RootNamespace>BluetoothTransfer.Receiver</RootNamespace>
    <Version>1.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BluetoothTransfer.Core\BluetoothTransfer.Core.csproj" />
  </ItemGroup>

</Project>
